### ISSUE TITLE
Tracking issue for documentation updates

### ISSUE THREAD

**Issue by jhaaaa** [xmtp/docs-xmtp-org#74]
This tracking issue lists all the documentation pages that need to be updated or reviewed for XMTP V3. Items with 🏗️ may require code updates.

- [ ]  /get-started/developer-quickstart. Content needs to be updated for V3. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/get-started/developer-quickstart)
- [ ] /get-started/examples. 🏗️ Example apps and tools need to be updated to use V3. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/get-started/examples)
- [ ]  /consent/subscribe. 🏗️ Update Broadcast, Subscribe, and Consent Proof functionality to use V3. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/consent/subscribe)
- [ ]  /consent/broadcast. 🏗️ Update Broadcast, Subscribe, and Consent Proof functionality to use V3. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/consent/broadcast)
- [ ]  /consent/consent-quickstarts. 🏗️ Update Broadcast, Subscribe, and Consent Proof functionality to use V3. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/consent/consent-quickstarts)
- [ ]  /consent/build-engagement. 🏗️ Update Broadcast, Subscribe, and Consent Proof functionality to use V3. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/consent/build-engagement)
- [ ]  /protocol/signatures. Content needs updating to remove V2 signature types for V3. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/protocol/signatures)
- [ ]  /get-started/references. Review with Eng to verify SDK references are building as intended.
- [ ]  /open-frames/open-frames. 🏗️ Open Frames need to be updated to use V3. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/open-frames/open-frames)
- [ ]  /open-frames/subscription-open-frames. 🏗️ Example subscription Open Frame needs to be updated to use V3. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/open-frames/subscription-open-frames)
- [ ]  /open-frames/transactional-open-frames. 🏗️ Example transactional Open Frame needs to be updated to use V3. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/open-frames/transactional-open-frames)
- [ ]  /protocol/xmtp-versions. Content needs to be updated to act as a deprecation schedule doc for V2 and V1.
- [ ] /protocol/portable-inbox. Content needs to be updated to reflect installations and history. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/protocol/portable-inbox)
- [ ]  /chat-widget/chat-widget. 🏗️ Update chat widgets to use V3. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/chat-widget/chat-widget)
- [ ] /content-types/content-types. Review with Eng to ensure code samples are up to date. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/content-types/content-types)
- [ ]  /content-types/remote-attachment. Review with Eng to ensure code samples are up to date. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/content-types/remote-attachment)
- [ ]  /content-types/reaction. Review with Eng to ensure code samples are up to date. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/content-types/reaction)
- [ ]  /content-types/reply. Review with Eng to ensure code samples are up to date. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/content-types/reply)
- [ ] /content-types/read-receipt. Review with Eng to ensure code samples are up to date. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/content-types/read-receipt)
- [ ]  /content-types/transaction-ref. Review with Eng to ensure code samples are up to date. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/content-types/transaction-ref)
- [ ] /content-types/custom. Review with Eng to ensure code samples are up to date. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/content-types/custom)
- [ ] /perf-ux/xmtp-metamask-snap. Review with Eng to ensure code samples use useSnaps and SnapKeystore. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/perf-ux/xmtp-metamask-snap)
- [ ]  /protocol/v3/message-history. 🏗️ Write content once the feature is ready.
- [ ]  /protocol/v3/smart-wallet. 🏗️ Write content once the feature is ready.
- [ ]  /dms/troubleshoot. Review with Dev Rel and GTM - start fresh for V3.
- [ ] /perf-ux/optimistic-sending. Review with Eng to see if this doc is necessary with V3. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/perf-ux/optimistic-sending)
- [ ] /perf-ux/get-featured. Review with Eng and GTM to refresh for V3. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/perf-ux/get-featured)
- [ ]  /perf-ux/debug-and-test. Review with Eng to refresh for V3; consider if xmtp-debug repo needs updates. [Link to legacy doc](https://docs-xmtp-org-git-xmtp-legacy-ephemerahq.vercel.app/perf-ux/debug-and-test)
- [ ] /protocol/protocols. Review with Eng to find the best way to convey protocol specs.
